-- MySQL Script generated by MySQL Workbench
-- Mon Sep  8 01:01:48 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema empuje_comunitario
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema empuje_comunitario
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `empuje_comunitario` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `empuje_comunitario` ;

-- -----------------------------------------------------
-- Table `empuje_comunitario`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empuje_comunitario`.`role` (
  `id_role` INT NOT NULL AUTO_INCREMENT,
  `name_rol` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_role`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `empuje_comunitario`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empuje_comunitario`.`user` (
  `activate` BIT(1) NULL DEFAULT NULL,
  `id_role` INT NOT NULL,
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `phone` VARCHAR(20) NULL DEFAULT NULL,
  `username` VARCHAR(50) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `last_name` VARCHAR(100) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_user`),
  UNIQUE INDEX `UKob8kqyqqgmefl0aco34akdtpe` (`email` ASC) VISIBLE,
  INDEX `FK6njoh3pti5jnlkowken3r8ttn` (`id_role` ASC) VISIBLE,
  CONSTRAINT `FK6njoh3pti5jnlkowken3r8ttn`
    FOREIGN KEY (`id_role`)
    REFERENCES `empuje_comunitario`.`role` (`id_role`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `empuje_comunitario`.`donation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empuje_comunitario`.`donation` (
  `amount` INT NULL DEFAULT NULL,
  `id_donation` INT NOT NULL AUTO_INCREMENT,
  `id_user_modification` INT NULL DEFAULT NULL,
  `id_user_registration` INT NULL DEFAULT NULL,
  `removed` BIT(1) NULL DEFAULT NULL,
  `date_modification` DATETIME(6) NULL DEFAULT NULL,
  `date_registration` DATETIME(6) NULL DEFAULT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `category` ENUM('ALIMENTO', 'JUGUETE', 'MEDICINA', 'ROPA') NULL DEFAULT NULL,
  PRIMARY KEY (`id_donation`),
  INDEX `FKlhnwi26ecpdtvy2mht6tmuewu` (`id_user_modification` ASC) VISIBLE,
  INDEX `FKjf53tlcyjqnjwvr3de7xo8x4a` (`id_user_registration` ASC) VISIBLE,
  CONSTRAINT `FKjf53tlcyjqnjwvr3de7xo8x4a`
    FOREIGN KEY (`id_user_registration`)
    REFERENCES `empuje_comunitario`.`user` (`id_user`),
  CONSTRAINT `FKlhnwi26ecpdtvy2mht6tmuewu`
    FOREIGN KEY (`id_user_modification`)
    REFERENCES `empuje_comunitario`.`user` (`id_user`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `empuje_comunitario`.`events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empuje_comunitario`.`events` (
  `id_event` INT NOT NULL AUTO_INCREMENT,
  `date_registration` DATETIME(6) NULL DEFAULT NULL,
  `name_event` VARCHAR(200) NOT NULL,
  `description_event` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id_event`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `empuje_comunitario`.`donations_at_events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empuje_comunitario`.`donations_at_events` (
  `id_donation` INT NOT NULL,
  `id_donation_at_event` INT NOT NULL AUTO_INCREMENT,
  `id_event` INT NOT NULL,
  `quantity_delivered` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_donation_at_event`),
  INDEX `FKkw5cutcrwi9evipks9jp6ecp0` (`id_donation` ASC) VISIBLE,
  INDEX `FK39m5cmdakq80ujqoq3jp4b2je` (`id_event` ASC) VISIBLE,
  CONSTRAINT `FK39m5cmdakq80ujqoq3jp4b2je`
    FOREIGN KEY (`id_event`)
    REFERENCES `empuje_comunitario`.`events` (`id_event`),
  CONSTRAINT `FKkw5cutcrwi9evipks9jp6ecp0`
    FOREIGN KEY (`id_donation`)
    REFERENCES `empuje_comunitario`.`donation` (`id_donation`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `empuje_comunitario`.`member_at_event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empuje_comunitario`.`member_at_event` (
  `id_event` INT NOT NULL,
  `id_member_at_event` INT NOT NULL AUTO_INCREMENT,
  `id_user` INT NOT NULL,
  PRIMARY KEY (`id_member_at_event`),
  INDEX `FK31beg3ivtyn444t6r7r3nfpm8` (`id_event` ASC) VISIBLE,
  INDEX `FKbbqt6010d6ptg6m5on0n7pbp5` (`id_user` ASC) VISIBLE,
  CONSTRAINT `FK31beg3ivtyn444t6r7r3nfpm8`
    FOREIGN KEY (`id_event`)
    REFERENCES `empuje_comunitario`.`events` (`id_event`),
  CONSTRAINT `FKbbqt6010d6ptg6m5on0n7pbp5`
    FOREIGN KEY (`id_user`)
    REFERENCES `empuje_comunitario`.`user` (`id_user`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
