extend type Query{
    # Devuelve todos los eventos con sus relaciones
    eventReportAll: [EventReportDTO]
}

extend type Query {
    eventReport(
        emailUser: String!,        # obligatorio
        startDate: String,         # opcional
        endDate: String,           # opcional
        withDonations: String      # "SI", "NO" o "AMBOS"
    ): [EventPerMonthDTO]
}

type EventPerMonthDTO {
    month: String
    events: [EventReportDTO]
}

type EventReportDTO {
    idEvent: ID
    nameEvent: String
    descriptionEvent: String
    dateRegistration: String
    members: [UserDTO]
    donations: [DonationAtEventDTO]
}

type UserDTO {
    fullName: String
    roleName: String
}

type DonationAtEventDTO {
    donation: DonationDTO
    quantity: Int
}

type DonationDTO {
    category: String
    description: String
}
