# ===========================
# Tipos y enums principales
# ===========================

type Operation {
  idOperation: ID!
  idOperationMessage: Int
  idOrganization: Int
  operationType: String
  activate: Boolean
  dateRegistration: String
  dateModification: String
}


# --- Tipo para los detalles individuales ---
type DonationDetail {
  description: String
  quantity: Int
}


# --- Tipo principal del reporte ---
type DonationReport {
  category: Category
  activate: Boolean
  totalQuantity: Int
  details: [DonationDetail]
}

enum Category {
  ROPA
  ALIMENTO
  JUGUETE
  UTIL_ESCOLAR
}

#FILTROS

input DonationFilterDTO {
  filterName: String!
  startDate: String
  endDate: String
  activate: Boolean
  category: Category
}

# ===========================
# Queries
# ===========================
type Query {
  
  operations: [Operation!]!

  donationReport(
    category: Category,
    startDate: String,
    endDate: String,
    activate: Boolean,
    isExternal: Boolean
    
  ): [DonationReport!]!

}

# ===========================
# Mutations
# ===========================

type Mutation {
  saveDonationFilter(input: DonationFilterDTO!, emailOrUsername: String!): Boolean
  deleteDonationFilter(idFilter: Int!, emailOrUsername: String!): Boolean

  updateDonationFilter(input: DonationFilterDTO!, emailOrUsername: String!): Boolean
}
