type Operation {
    idOperation: ID!
    idOperationMessage: Int
    idOrganization: Int
    operationType: String
    activate: Boolean
    dateRegistration: String
    dateModification: String
}

type DonationReport {
    category: String
    activate: Boolean
    totalQuantity: Int
}

enum Category {
    ROPA
    ALIMENTO
    JUGUETE
    UTIL_ESCOLAR
}

type Query {
    operations: [Operation!]!
    donationReport(
        category: Category,
        startDate: String,
        endDate: String,
        activate: Boolean
    ): [DonationReport!]!
}

